// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vksrhtlmfmmuxikvdrda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrc3JodGxtZm1tdXhpa3ZkcmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMDE0MzYsImV4cCI6MjA3OTg3NzQzNn0.GOoAJ0Hp5l5OaUhXg7ZI_E3x8BJiFSyCx6YKX1VILHA";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Only use localStorage in the browser
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});